# Generated by Django 5.2.8 on 2025-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('habitat', models.CharField(max_length=20)),
                ('caretaker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('experience', models.FloatField()),
                ('phone_number', models.IntegerField()),
                ('specialization', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='donated_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('reason_for_donation', models.CharField(max_length=40)),
            ],
        ),
    ]
