# Generated by Django 5.2.8 on 2025-11-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoodb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='caretaker',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='donated_by',
            name='email',
        ),
    ]
